#define _GNU_SOURCE
#include <sched.h>
#include <semaphore.h>
#include <stdio.h>

#define WRITE_CLONE_FLAG(f) do { printf(#f " = 0x%08x\n", f); } while (0)

void write_clone_flags(void) {
    WRITE_CLONE_FLAG(CLONE_CHILD_CLEARTID);
    WRITE_CLONE_FLAG(CLONE_CHILD_SETTID);
    //WRITE_CLONE_FLAG(CLONE_CLEAR_SIGHAND);
    WRITE_CLONE_FLAG(CLONE_DETACHED);
    WRITE_CLONE_FLAG(CLONE_FILES);
    WRITE_CLONE_FLAG(CLONE_FS);
    //WRITE_CLONE_FLAG(CLONE_INTO_CGROUP);
    WRITE_CLONE_FLAG(CLONE_IO);
    WRITE_CLONE_FLAG(CLONE_NEWCGROUP);
    WRITE_CLONE_FLAG(CLONE_NEWIPC);
    WRITE_CLONE_FLAG(CLONE_NEWNET);
    WRITE_CLONE_FLAG(CLONE_NEWNS);
    WRITE_CLONE_FLAG(CLONE_NEWPID);
    WRITE_CLONE_FLAG(CLONE_NEWUSER);
    WRITE_CLONE_FLAG(CLONE_NEWUTS);
    WRITE_CLONE_FLAG(CLONE_PARENT);
    WRITE_CLONE_FLAG(CLONE_PARENT_SETTID);
    //WRITE_CLONE_FLAG(CLONE_PID);
    WRITE_CLONE_FLAG(CLONE_PIDFD);
    WRITE_CLONE_FLAG(CLONE_PTRACE);
    WRITE_CLONE_FLAG(CLONE_SETTLS);
    WRITE_CLONE_FLAG(CLONE_SIGHAND);
    //WRITE_CLONE_FLAG(CLONE_STOPPED);
    WRITE_CLONE_FLAG(CLONE_SYSVSEM);
    WRITE_CLONE_FLAG(CLONE_THREAD);
    WRITE_CLONE_FLAG(CLONE_UNTRACED);
    WRITE_CLONE_FLAG(CLONE_VFORK);
    WRITE_CLONE_FLAG(CLONE_VM);
}

int main(void) {
    write_clone_flags();
    printf("\n");
    printf("SIZEOF_SEM_T = %zd\n", sizeof(sem_t));

    return 0;
}
