#define _GNU_SOURCE
#include <sched.h>
#include <semaphore.h>
#include <stdio.h>
#include <sys/mount.h>

#define WRITE_CLONE_FLAG(f) do { printf(#f " = %#010x\n", f); } while (0)
#define WRITE_MOUNT_FLAG(f) do { printf(#f " = %#010lx\n", (unsigned long)f); } while (0)

void write_clone_flags(void) {
    WRITE_CLONE_FLAG(CLONE_CHILD_CLEARTID);
    WRITE_CLONE_FLAG(CLONE_CHILD_SETTID);
    //WRITE_CLONE_FLAG(CLONE_CLEAR_SIGHAND);
    WRITE_CLONE_FLAG(CLONE_DETACHED);
    WRITE_CLONE_FLAG(CLONE_FILES);
    WRITE_CLONE_FLAG(CLONE_FS);
    //WRITE_CLONE_FLAG(CLONE_INTO_CGROUP);
    WRITE_CLONE_FLAG(CLONE_IO);
    WRITE_CLONE_FLAG(CLONE_NEWCGROUP);
    WRITE_CLONE_FLAG(CLONE_NEWIPC);
    WRITE_CLONE_FLAG(CLONE_NEWNET);
    WRITE_CLONE_FLAG(CLONE_NEWNS);
    WRITE_CLONE_FLAG(CLONE_NEWPID);
    WRITE_CLONE_FLAG(CLONE_NEWUSER);
    WRITE_CLONE_FLAG(CLONE_NEWUTS);
    WRITE_CLONE_FLAG(CLONE_PARENT);
    WRITE_CLONE_FLAG(CLONE_PARENT_SETTID);
    //WRITE_CLONE_FLAG(CLONE_PID);
    WRITE_CLONE_FLAG(CLONE_PIDFD);
    WRITE_CLONE_FLAG(CLONE_PTRACE);
    WRITE_CLONE_FLAG(CLONE_SETTLS);
    WRITE_CLONE_FLAG(CLONE_SIGHAND);
    //WRITE_CLONE_FLAG(CLONE_STOPPED);
    WRITE_CLONE_FLAG(CLONE_SYSVSEM);
    WRITE_CLONE_FLAG(CLONE_THREAD);
    WRITE_CLONE_FLAG(CLONE_UNTRACED);
    WRITE_CLONE_FLAG(CLONE_VFORK);
    WRITE_CLONE_FLAG(CLONE_VM);
}

void write_mount_flags(void) {
    WRITE_MOUNT_FLAG(MS_REMOUNT);
    WRITE_MOUNT_FLAG(MS_BIND);
    WRITE_MOUNT_FLAG(MS_SHARED);
    WRITE_MOUNT_FLAG(MS_PRIVATE);
    WRITE_MOUNT_FLAG(MS_SLAVE);
    WRITE_MOUNT_FLAG(MS_UNBINDABLE);
    WRITE_MOUNT_FLAG(MS_MOVE);
    WRITE_MOUNT_FLAG(MS_DIRSYNC);
    WRITE_MOUNT_FLAG(MS_LAZYTIME);
    WRITE_MOUNT_FLAG(MS_MANDLOCK);
    WRITE_MOUNT_FLAG(MS_NOATIME);
    WRITE_MOUNT_FLAG(MS_NODEV);
    WRITE_MOUNT_FLAG(MS_NODIRATIME);
    WRITE_MOUNT_FLAG(MS_NOEXEC);
    WRITE_MOUNT_FLAG(MS_NOSUID);
    WRITE_MOUNT_FLAG(MS_RDONLY);
    WRITE_MOUNT_FLAG(MS_REC);
    WRITE_MOUNT_FLAG(MS_RELATIME);
    WRITE_MOUNT_FLAG(MS_SILENT);
    WRITE_MOUNT_FLAG(MS_STRICTATIME);
    WRITE_MOUNT_FLAG(MS_SYNCHRONOUS);
    WRITE_MOUNT_FLAG(MS_NOSYMFOLLOW);
}

int main(void) {
    write_clone_flags();
    printf("\n");
    write_mount_flags();
    printf("\n");
    printf("SIZEOF_SEM_T = %zd\n", sizeof(sem_t));

    return 0;
}
